apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  selector:
    app: jenkins
  ports:
    - name: jenkins-svc
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer