```
apiVersion: batch/v1
kind: Job
metadata: 
  name: hellojob
spec:
  backoffLimit: 5
  template:
    metadata:
      name: jobcont
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mycont
          image: httpd
          ports: 
            - containerport: 80
          args:
            - slepp
            - 10s