apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-pvol
          mountPath: /var/lib/mysql
      env:
        - Name:
          Value:
        - Name:
          Value:
  volumes:
    - name: mysql-pvol
      persistentVolumeClaim:
        claimName: mysql-pvc
       
      
      
      