---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dashboard-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    name: dashboard-pod
    kind: Pod
  targetCPUUtilizationPercentage: 60
    