---
apiVersion: v1
kind: Pod
metadata:
  name: dashboard-pod
  labels:
    app: dashboard
spec:
  container:
    - name: dashboard-cont
      image: shaikkhajaibrahim/dashboardservice:1.0.0
      ports:
        - containerPort: 80